spring.data.mongodb.uri=mongodb+srv://patillakhan25:x5V2OnjBeo6hRWZJ@journalappcluster.isnzo8y.mongodb.net/?retryWrites=true&w=majority&appName=JournalAppCluster
spring.application.name=Journal app
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true